import type { Metadata, Viewport } from 'next'
import { Archivo, Be_Vietnam_Pro, JetBrains_Mono } from 'next/font/google'
import GrainOverlay from '@/components/server/GrainOverlay'
import ScrollProgress from '@/components/client/ScrollProgress'
import WebVitals from '@/components/client/WebVitals'
import Providers from './providers'
import { env } from '@/lib/env'
import './globals.css'

const archivo = Archivo({
  subsets: ['latin', 'latin-ext', 'vietnamese'],
  axes: ['wdth'],
  variable: '--font-archivo',
  display: 'swap',
})

// Body: Be Vietnam Pro — drawn for Vietnamese diacritics, so prose reads clean.
const beVietnam = Be_Vietnam_Pro({
  subsets: ['latin', 'vietnamese'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-be-vietnam',
  display: 'swap',
})

const jetbrains = JetBrains_Mono({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-jetbrains',
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL(env.NEXT_PUBLIC_SITE_URL),
  title: {
    default: 'KingMC · Máy chủ Minecraft #2 Việt Nam',
    template: '%s · KingMC',
  },
  description:
    'KingMC · Máy chủ Minecraft #2 Việt Nam. KingSMP, Mega Earth, Battle Royale. IP: kingmc.vn',
  openGraph: {
    type: 'website',
    locale: 'vi_VN',
    siteName: 'KingMC',
    // Dynamic share image with live player count, generated by app/og/route.tsx
    images: [
      {
        url: '/og',
        width: 1200,
        height: 630,
        type: 'image/png',
        alt: 'KingMC · Máy chủ Minecraft Việt Nam',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: ['/og'],
  },
  icons: { icon: '/favicon.png' },
}

export const viewport: Viewport = {
  themeColor: '#0B1018',
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="vi"
      data-theme="editorial"
      className={`${archivo.variable} ${beVietnam.variable} ${jetbrains.variable}`}
      suppressHydrationWarning
    >
      <body
        className="bg-ink text-on-surface min-h-screen font-sans antialiased"
        suppressHydrationWarning
      >
        <WebVitals />
        <GrainOverlay />
        <ScrollProgress />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
